# -*- coding: utf-8 -*-
"""Copy of Com Eng Math 2 - 1/2022 - Assignment 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F7QU7dtlURmeGNntLAfvypk1zAUl5TPQ

#  **<<< Only Problem 2 and 3 will be graded >>>**
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import numpy as np
import IPython.display as ipd
# %matplotlib inline
import os
from scipy import signal,fftpack
from skimage.io import imread
import cv2

"""## Problem 1
Find the Fourier tranform of the following signals in terms of $X(j\omega)$, the Fourier tranform of $x(t)$
$ \left( \mathscr{F} \left\{ x(t) \right\} = X(j\omega) \right)  $

1. $x(-t)$
1. $x_e(t) = \frac{x(t) + x(-t)}{2}$
1. $x_o(t) = \frac{x(t) - x(-t)}{2}$

## Problem 2
Let $  \mathscr{F} \left\{ x(t) \right\} = X(j\omega) = \textrm{rect} \left[ (\omega-1)/2\right]  $. Find Fourier tranform of

1. $x(-2t+4)$
1. $(t-1)x(t-1)$
1. $ t\frac{dx(t)}{dt}$
1. $ x(2t-1)\exp[-j2t]$
1. $ x(t)*x(t-1)$
"""

# each answer and solution are in write-up file

"""## Problem 3

For each of the following Fourier transform ($X(j\omega)$), use Fourier transform properties to determine the corresponding time-domain signal ($x(t)$)

1. $X(j\omega) = u(\omega) - u(\omega -2)$
2. $X(j\omega) = \cos(2\omega)\sin \left(\frac{\omega}{2} \right)$
"""

# each answer and solution are in write-up file

"""## Problem 4

Proof

$\int_{-\infty}^{\infty} {|x(t)|}^2 dt = \frac{1}{2\pi} \int_{-\infty}^{ \infty } |X(j\omega)|^2 d\omega$

## Problem 5



Determine a signal $x(t)$ which has its Fourier transform

$X(j\omega) = \delta(\omega)-\delta(\omega-a_0\pi)-\delta(\omega-a_1)$

and the impulse response in time-domain is  $h(t) = u(t) - u(t-2b_0)$



1.   Show how to find $x(t)$ and determine whether it is periodic?
2.   Show how to find $y(t) = x(t) * h(t) $ and determine whether it is periodic?

Verify you results by sketching $x(t)$, $h(t)$, $y(t)$, $X(j\omega)$, $H(j\omega)$ and $Y(j\omega)$. Note that for the complex number, plot only its magnitude.
"""

