# -*- coding: utf-8 -*-
"""Copy of AB testing 2022 (Student).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S9wdq-kvvmHztCfJTJfSNmwIvYAGnUuS

Do problem 1, 2, 3, 9, 10

## 1. Appropriate task to perform A/B test

Which of the following use cases can you reliably conduct an A/B test? (True/False)

1.1. Frontend person wants to change color of the 'Go' button on a search bar. Will it increase conversion rate?

1.2. The data team created four versions of machine learning model for product recommendations to new users of an app. Which one is the best?

1.3. Two managers from different factions have Layout A and Layout B for a physical convenience store. Which one should we use?

1.4. Mr. Rabbito thinks offline stores are the best channel to distribute our products, whereas Ms. Rakko thinks online websites are the way to go. Who is right?

1.5. Your boss wants to add a premium version to your freemium service. Is it a good idea?

1.6. The backend team came up with a new setup that they think will speed up the website load time. Should we implement this change?

1.7. Kuruma Inc., a car dealer, wants to change the banner on their homepage to see if it will attract more repeated customers. Average time between purchase of the car company is 5 years. How do you know if the banner change has an effect?

1.8. Your company undergoes a total revamp of its corporate identity. Is it the right call?

1.9. Elastic ninja at your company wants to show 15 products on the first page of search results instead of 20 products. Should you allow them?

1.10. Marketing person wants to know who respond better to our ads campaigns between iOS users and Android users. How to tell?

## 2. Choose the method

What are the metrics you should use for the following A/B tests? Assume that the granularities are: page views and unique visitors.

2.1. Which button colors will make customers find it more easily? clicks / __

2.2. Which sets of products on a landing page will make customers more likely to buy? purchases / __

2.3. Which types of promotion coupons will be more effective? purchases / __

2.4. Which website layouts will attract more customers to click on sign up button? clicks / __

## 3. Choose the period

Based on the transaction table below,

3.1. what are the event-based conversion rate of 2020-11?

3.2. what are cohort-based conversion rate of 2020-11?

Assume 7-day attribution period. Conversion rate is calculated by purchases / unique users.

| date       | user | event    |
|------------|------|----------|
| 2020-11-01 | A    | visit    |
| 2020-11-01 | A    | purchase |
| 2020-11-05 | B    | visit    |
| 2020-11-13 | B    | visit    |
| 2020-11-30 | C    | visit    |
| 2020-12-05 | C    | purchase |

## 4. Familarity with the incoming data

Give 3 examples of values that are usually distributed in the following manner (do not use examples from class):

4.1. Bernoulli/Binomial distributions: __, __, __

4.2. Normal/Student t's distribution: __, __, __

4.3. Exponential distribution: __, __, __

4.4. Poisson distribution: __, __, __

## 5. Design experiments

Which variables should you control for in an A/B test of the following cases?

5.1. We want to test if SMOKING -> CANCER (Smoking causes cancer) and we know that AGE -> SMOKING and AGE -> CANCER. We should control for __

5.2. We want to test if GUN OWNERSHIP -> CRIMES and we know that GUN OWNERSHIP -> GUN SALES and CRIMES -> GUN SALES. We should control for __

5.3. We want to test if CROP BURNING -> LUNG DISEASES and we know that CROP BURNING -> PM2.5 and PM2.5 -> LUNG DISEASES. We should control for __

## 6. LLN
The Law of Large Numbers (LLN) says that sample mean will converge to expectation as sample size grows. Assuming that this is true, prove that sample variance will converge to variance as sample size grows.

## 7. P-value

What is p-value? (Choose one or more)

7.1. Assuming that the null hypothesis is true, what is the probability of observing the current or more extreme data.

7.2. Based on the observed data, what is the probability of the null hypothesis being true.

7.3. Based on the observed data, what is the probability of the null hypothesis being false.

7.4. Assuming that our hypothesis is true, what is the chance that we reject the null hypothesis.

## 8. False positive

If we conduct a frequentist statistical test at 5% significance level repeatedly for 4,000 times, how many times can we expect to have statistically significant results even if group A and B are exactly the same?

## 9. Hamster Inc. and His Color Package

Hamster Inc. once again wants to test the conversion rates between package colors of its sunflower seeds; this time it is Red Package vs Gold Package. The Red Package is the existing group with average conversion rate of 11%. If they think the minimum detectable effect is 1% and want to make a 80/20 control/test split, how many unique users should see each package color before we decide which one performs better? Assume that they are testing at significance level of 15%. Show your work.
"""

import scipy.stats as st
import math

cr = 0.11
std = ((cr)*(1-cr))**0.5
mde = 0.01
m = 80/20
sig = 0.15
power = 0.80

z_sig = st.norm.ppf(1-sig, loc = 0, scale = 1)
z_pow = st.norm.ppf(power, loc = 0, scale = 1)

n = ((m+1)/m)*((z_sig+z_pow)*std/mde)**2
print("n :", math.ceil(n))
print("Sample size for Red Package", int(m*math.ceil(n)))
print("Sample size for Gold Package", math.ceil(n))

"""## 10. Hamster Inc. and His A/B Testing Experiment

Let us say Hamster Inc. ran the experiment and got the following results.

  10.1. At significance level of 7%, which variation should be chosen to run at 100% traffic? Show your work.

  10.2. What are the confidence intervals at 7% significance of conversion rates for Red and Gold? Show your work.

| campaign_id | clicks | conv_cnt | conv_per |
|------------:|-------:|---------:|---------:|
|         Red |  59504 |     5901 | 0.099170 |
|        Gold |  58944 |     6012 | 0.101995 |
"""

# TODO#10.1
sig = 0.07

red_all = 59504
red_conv = 5901
gold_all = 58944
gold_conv = 6012

red_cr = red_conv/red_all
gold_cr = gold_conv/gold_all

both_std_n = (gold_cr*(1-gold_cr)/gold_all+red_cr*(1-red_cr)/red_all)**0.5
z = (gold_cr - red_cr)/both_std_n
p_val = st.norm.cdf(z)

print("P-value :", p_val)
if p_val >= 1-sig:
  print("Reject H0")
else:
  print("Not Reject H0")

# TODO#10.2
# overall
sig = 0.07

Z = st.norm.ppf(1-sig/2)
cr_u = gold_cr - red_cr

lower = cr_u-Z*both_std_n
upper = cr_u+Z*both_std_n
print("Confidence Interval is [", lower, ",", upper, "]")

# red&gold
red_lower = red_cr-Z*(red_cr*(1-red_cr)/red_all)**0.5
red_upper = red_cr+Z*(red_cr*(1-red_cr)/red_all)**0.5

gold_lower = gold_cr-Z*(gold_cr*(1-gold_cr)/gold_all)**0.5
gold_upper = gold_cr+Z*(gold_cr*(1-gold_cr)/gold_all)**0.5

print("Confidence Interval for red is [", red_lower, ",", red_upper, "]")
print("Confidence Interval for gold is [", gold_lower, ",", gold_upper, "]")

"""## 11. Understanding of A/B Testing

Which of the following are true about frequentist A/B tests? (True/False)

  11.1. It does not tell us the magnitude of the difference between control and test groups.

  11.2. We can never know when to stop the experiments.

  11.3. We can never determine if the null hypothesis being true.

  11.4. We can run one or as many experiments as we want using the same significance level.

  11.5. If we have too many samples in each group, the validity of the test can be jeopardized.

  11.6. If you have set up the experiment based on desired minimum detectable effect and significance level, statististical significance is the only factor in determining which group is the better one.

  11.7. We can only test difference between two proportions.

  11.8. More samples in control and test groups are always better.
"""