# -*- coding: utf-8 -*-
"""Copy of Com Eng Math 2 - 1/2022 - Assignment 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WNn2AZ6_O187C1YkTxucCuJgyeLL-Igi

# **<<< Only Problem 1.1 and 2.1  will be graded >>>**

## Problem 1.1  (DFT)

Given the DFT spectrum $X[k]$, express the corresponding time-domain signal
$x[n]$ in terms of its constituent real sinusoids.

1. $X[0]=3,X[1]= \frac{1}{\sqrt{2}}−j\frac{1}{\sqrt{2}} ,X[2]=−2,
X[3]= \frac{1}{\sqrt{2}}+j\frac{1}{\sqrt{2}}$

2. $X[0]=-2,X(1)= \sqrt{3}+j1 ,X[2]=3,X[3]= \sqrt{3}-j1$

3. $X[0]=1,X[1]= 2-j2\sqrt{3} ,X[2]=-3,X[3]= 2+j2\sqrt{3}$
"""

# Check answer of Problem 1.1.1
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal,fftpack
import math

X_k = [complex(3, 0), complex(1/2**0.5,-1/2**0.5), complex(-2, 0), complex(1/2**0.5,1/2**0.5)]
x_n = np.fft.ifft(X_k)

def writeup_x_n(n):
  return 3/4 - math.cos(n*math.pi)/2 + math.cos(n*math.pi/2-math.pi/4)/2

for i in range(4):
  correct = "Correct" if abs(x_n[i]-writeup_x_n(i)) < 0.000001 else "Wrong"
  print("x["+str(i)+"] :", correct)

# Check answer of Problem 1.1.2
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal,fftpack

X_k = [complex(-2, 0), complex(3**0.5,1), complex(3, 0), complex(3**0.5,-1)]
x_n = np.fft.ifft(X_k)

def writeup_x_n(n):
  return -1/2 + 3*math.cos(n*math.pi)/4 + math.cos(n*math.pi/2+math.pi/6)

for i in range(4):
  correct = "Correct" if abs(x_n[i]-writeup_x_n(i)) < 0.000001 else "Wrong"
  print("x["+str(i)+"] :", correct)

# Check answer of Problem 1.1.3
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal,fftpack

X_k = [complex(1, 0), complex(2,-2*(3**0.5)), complex(-3, 0), complex(2,2*(3**0.5))]
x_n = np.fft.ifft(X_k)

def writeup_x_n(n):
  return 1/4 - 3*math.cos(n*math.pi)/4 + 2*math.cos(n*math.pi/2-math.pi/3)

for i in range(4):
  correct = "Correct" if abs(x_n[i]-writeup_x_n(i)) < 0.000001 else "Wrong"
  print("x["+str(i)+"] :", correct)

"""## Problem 1.2 (DFT) (Optional)
Show that if $x[n]$ is real sequence, $X[N-k]=X^{*}[k]$

## Problem 2.1 (DTFT)

Use the properties of the discrete-time transform to determine $X(e^{j\omega})$ for the following sequences

1. $x[n] = n \left( \frac{1}{3} \right)^{|n|}$

2. $x[n] = a^{n} \cos (\Omega_0 n) \cdot  u[n] , \, |a|< 1 $

3. $x[n] =  (n+1)a^n \cdot u[n], \, |a|< 1 $
"""

# In write-up file

"""## Problem 2.2 (DTFT)

Find the discrete-time sequence $x[n]$ with tranforms in range $0 \leq \omega < 2\pi$ as follows

1. $X(e^{j\omega}) = -j\pi\delta \left( \omega - \frac{\pi}{3} \right)
 + \pi\delta \left( \omega - \frac{2\pi}{3} \right)
 + \pi\delta \left( \omega - \frac{4\pi}{3} \right)
 + j\pi\delta \left( \omega - \frac{5\pi}{3} \right) $

2. $X(e^{j\omega}) = \frac{1 - \frac{5}{6}e^{-j\omega} }{1 + \frac{1}{12}e^{-j\omega} - \frac{1}{12}e^{-j2\omega} }$
"""